### ISSUE TITLE
NO LABELS IN THIS DATABASE

### ISSUE THREAD

**Issue by AlbertoCOHUB** [justinelliotmeyers/MOROCCO_OFFICIAL_SHAPEFILE#2]
NO LABELS IN THIS DATABASE

**Comment by justinelliotmeyers** [comment]
This is the way the raw data came. You can add from several open resources if that is what you need for your use case.

**Comment by AlbertoCOHUB** [comment]
Of course these geometries are worth, just saying one could not be able to leverage because of it,
Anyway thanks for the prompt answer

**Comment by justinelliotmeyers** [comment]
you can use them for thousands of things without attributes. but yes, value mainly lives in the attributes.

back apply admin names from numerous resources:
https://geonames.nga.mil/geonames/GNSData/
https://data.humdata.org/dataset/cod-ab-mar

let me know if you need more or cant figure it out. 

Cheers!
